- name: Configured Azure HCI AKS
  hosts: hcimanager
  gather_facts: false

  tasks:
  - name: powershell Initialize AksHciNode
    ignore_errors: True
    ansible.windows.win_powershell: 
      script: |
        Get-AksHciNodePool -clusterName akshciclus001
    register: homedir_out
      
  - name: print init output
    debug:
      msg: "init status:  {{ homedir_out }}"