- name: Configured Azure HCI AKS
  hosts: hcimanager
  #connection: local
  gather_facts: false

  vars_files: 
    - vars/cluster_vars.yml

  tasks:
  - name: create script directory
    win_file:
      path: "{{ pwshScriptHome }}"
      state: directory
  - name: write aks env variables file
    template:
      src: aks_variables.ps1.j2
      dest: "{{ pwshScriptHome }}\\aks_variables.ps1"
  - name: write the aks config hci script to server
    template:
      src: config_aks_hci.ps1.j2
      dest: "{{ pwshScriptHome }}\\config_aks_hci.ps1"
  - name: copy dependency file(may deprecate for install_dependencies.yml playbook)
    ansible.windows.win_copy:
      src: files/installDependencies.ps1
      dest: "{{ pwshScriptHome }}\\installDependencies.ps1"
  - name: Install AksHci
    ansible.windows.win_shell: "{{ pwshScriptHome }}\\config_aks_hci.ps1 >> {{ pwshScriptHome }}\\config_aks_hci.txt"
    args:
      chdir: "{{ pwshScriptHome }}"

