- name: Create AKS Cluster
  hosts: hcimanager
  #connection: local
  gather_facts: false

  vars_files: 
    - vars/cluster_vars.yml

  tasks:
  - name: create script directory
    win_file:
      path: "{{ pwshScriptHome }}"
      state: directory
  - name: Copy install dependencies powershell script
    ansible.windows.win_copy:
      src: files/installDependencies.ps1
      dest: "{{ pwshScriptHome }}\\installDependencies.ps1"
  - name: write aks env variables file
    template:
      src: aks_variables.ps1.j2
      dest: "{{ pwshScriptHome }}\\aks_variables.ps1"
  - name: write create aks cluster script to server
    template:
      src: create_aks_cluster.ps1.j2
      dest: "{{ pwshScriptHome }}\\create_aks_cluster.ps1"
  - name: Create AKS cluster
    ansible.windows.win_shell: "{{ pwshScriptHome }}\\create_aks_cluster.ps1 >> {{ pwshScriptHome }}\\create_aks_cluster.txt"
    args:
      chdir: "{{ pwshScriptHome }}"
      
