- name: Create AKS Cluster
  hosts: hcimanager
  

  vars_files: 
    - vars/cluster_vars.yml

  tasks:
  - name: install dependencies
    include_tasks: tasks/install_dependencies.yml
  
  - name: build variables
    include_tasks: tasks/build_variables_file.yml
  
  - name: write create aks cluster script to server
    template:
      src: create_aks_cluster.ps1.j2
      dest: "{{ pwshScriptHome }}\\create_aks_cluster.ps1"

  - name: check if log file exists
    win_stat:
      path: "{{ pwshScriptHome }}\\create_aks_cluster.log"
    register: log_file_name

  - name: Move log file
    ansible.windows.win_shell: "mv {{ pwshScriptHome }}\\create_aks_cluster.log {{ pwshScriptHome }}\\create_aks_cluster.{{ansible_date_time.epoch}}.log"
    args:
      chdir: "{{ pwshScriptHome }}"
    when: log_file_name.stat.exists
    
  - name: Create AKS cluster
    ansible.windows.win_shell: "{{ pwshScriptHome }}\\create_aks_cluster.ps1 >> {{ pwshScriptHome }}\\create_aks_cluster.log"
    args:
      chdir: "{{ pwshScriptHome }}"
      
