- name: Create AKS Cluster
  hosts: hcimanager
  #connection: local
  gather_facts: false

  vars_files: 
    - vars/cluster_vars.yml

  tasks:
  - name:
    delegate_to: localhost
    template:
      src: create_aks_cluster.ps1.j2
      dest: create_aks_cluster.ps1
  - name: create script directory
    win_file:
      path: "{{ pwshScriptHome }}"
      state: directory
  - name: Copy install dependencies powershell script
    ansible.windows.win_copy:
      src: files/installDependencies.ps1
      dest: "{{ pwshScriptHome }}\\installDependencies.ps1"
      backup: yes
  - name: Copy AKS New Cluster powershell script
    ansible.windows.win_copy:
      src: create_aks_cluster.ps1
      dest: "{{ pwshScriptHome }}\\create_aks_cluster.ps1"
