- name: Manage Hyper-V VMs
  hosts: hcimanager
  
  vars_files: 
    - vars/manage_hci_vms_vars.yml

  tasks:
  - name: install dependencies
    include_tasks: tasks/install_dependencies.yml

  - name: Create VMs
    include_tasks: tasks/create_vm.yml
    with_items: "{{ hci_vms }}"
    when: vm.state == 'present'
    loop_control:
      loop_var: vm
  
  - name: Add cluster role
    include_tasks: tasks/add_vm_cluster_role.yml
    with_items: "{{ hci_vms }}"
    when: 
      - vm.state == 'present'
      - vm.cluster
    loop_control:
      loop_var: vm


  - name: Delete VMs
    include_tasks: tasks/delete_vm.yml
    with_items: "{{ hci_vms }}"
    when: vm.state == 'absent'
    loop_control:
      loop_var: vm
  
  
  
      
