pwshScriptHome: "C:\\automation\\scripts"
pwshScriptLogs: "{{ pwshScriptHome }}\\logs"
vmDrive: "V:\\"
imageDir: "VMs\\Templates"
vm_config_path: "V:\\VMs"
install_win_dependencies: false

hci_vms:
  - name: "web-1"
    state: present
    type: dhcp
    defaut_generation: 1
    cpu: 2   
    memory: 4096MB
    network_switch: "InternalNAT"
    src_vhd: "{{imageDir}}\\ubuntu.vhdx"
    cluster: false
  


  