pwshScriptHome: "C:\\automation\\scripts"
pwshScriptLogs: "{{ pwshScriptHome }}\\logs"
install_win_dependencies: false
resourceGroup: 'aks-poc-resources'
#Azure region to connect your Azure Arc enabled Kubernetes
location: centralus
#subscription to connect your Azure Arc enabled Kubernetes
subscriptionId: "{{ lookup('env', 'SUBSCRIPTION_ID') }}"
#appID of the service principal created
appId: "{{ lookup('env', 'APP_ID') }}"
#password of the service principal created
service_principal_password: "{{ lookup('env', 'CLIENT_SECRET') }}"
#tenantID
tenantId: "{{ lookup('env', 'TENANT_ID') }}"

#defaults
defaultControlPlaneNodeCount: 1 #should be either 1, 3, or 5
defaultKubernetesVersion: v1.22.4
arcEnabled: true