- name: create vm HD Directory
  win_file:
    path: "{{ vm_config_path }}\\{{ vm.name }}\\virtual\ hard\ drives"
    state: directory

- name: Check whether vhdx already exists
  win_stat:
    path: "{{ vm_config_path }}\\{{ vm.name }}\\virtual\ hard\ drives\\{{vm.name}}.vhdx"
    get_checksum: false
  register: file_info

- name: Clone vhdx 
  win_copy:
    src: "{{vm.src_vhd}}"
    dest: "{{ vm_config_path }}\\{{ vm.name }}\\virtual\ hard\ drives\\{{vm.name}}.vhdx"
    remote_src: True
  when: file_info.stat.exists == false
  

- name: Create VM
  win_hyperv_guest:
    name: "{{vm.name}}"
    generation: "{{vm.defaut_generation}}"
    cpu: "{{vm.cpu}}"
    memory: "{{vm.memory}}"
    network_switch: "{{vm.network_switch}}"
    diskpath: "{{ vm_config_path }}\\{{ vm.name }}\\virtual\ hard\ drives\\{{vm.name}}.vhdx"
    vm_config_path: "{{vm_config_path}}"
    state: present
  register: new_vms

- name: print vm results
  debug: 
    msg: "results are {{new_vms}}"

- name: Poweron VM
  win_hyperv_guest:
    name: "{{vm.name}}"
    state: started 