- name: write aks env variables file
  template:
    src: modify_cluster_variables.ps1.j2
    dest: "{{ pwshScriptHome }}\\modify_cluster_variables.ps1"
  
- name: write create aks cluster script to server
  ansible.windows.win_copy:
    src: files/create_aks_cluster.ps1
    dest: "{{ pwshScriptHome }}\\create_aks_cluster.ps1"

- name: set create log file name
  set_fact:
    create_log_file_name: "create_aks_workload_{{ cluster.clusterName }}_{{ansible_date_time.epoch}}.log"
  
- name: Create AKS cluster
  ansible.windows.win_shell: "{{ pwshScriptHome }}\\create_aks_cluster.ps1 >> {{ pwshScriptLogs }}\\{{ create_log_file_name }}"
  args:
    chdir: "{{ pwshScriptHome }}"