- name: Check whether vhdx already exists
  win_stat:
    path: "{{ vm_config_path }}\\{{ vm.name }}\\virtual\ hard\ drives\\{{vm.name}}.vhdx"
    get_checksum: false
  register: file_info

- name: Poweroff VM
  win_hyperv_guest:
    name: "{{vm.name}}"
    state: stopped 
  when: file_info.stat.exists 

- name: remove vm cluster role
  ansible.windows.win_shell: "Remove-ClusterGroup -VMId (Get-VM -Name {{vm.name}}).VMId -RemoveResources -Force"
  when: vm.cluster


- name: Delete VM
  win_hyperv_guest:
    name: "{{vm.name}}"
    state: absent
  register: deleted_vms

- name: Delete VM from Disk
  win_file:
    path: "{{ vm_config_path }}\\{{ vm.name }}"
    state: absent
  register: deleted_files

