- name: create script directory
  win_file:
    path: "{{ pwshScriptHome }}"
    state: directory

- name: create log directory
  win_file:
    path: "{{ pwshScriptLogs }}"
    state: directory

- name: install base dependencies
  ansible.windows.win_powershell:
    script: |
      Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
      Install-PackageProvider -Name NuGet -Force -Confirm:$false
      Install-Module -Name PowershellGet -Force -Confirm:$false
  when: install_win_dependencies


- name: install AksHCI dependencies
  ansible.windows.win_powershell:
    script: |
      Install-Module -Name AksHci -Repository PSGallery -AcceptLicense -Force -Confirm:$false
  when: install_win_dependencies



