- name: write aks env variables file
  template:
    src: remove_cluster_variables.ps1.j2
    dest: "{{ pwshScriptHome }}\\remove_cluster_variables.ps1"
  
- name: write remove aks cluster script to server
  ansible.windows.win_copy:
    src: remove_aks_cluster.ps1
    dest: "{{ pwshScriptHome }}\\remove_aks_cluster.ps1"

- name: set remove log file name
  set_fact:
    remove_log_file_name: "remove_aks_workload_{{ cluster.clusterName }}_{{ansible_date_time.epoch}}.log"
  
- name: Remove AKS cluster
  ansible.windows.win_shell: "{{ pwshScriptHome }}\\remove_aks_cluster.ps1 >> {{ pwshScriptLogs }}\\{{ remove_log_file_name }}"
  args:
    chdir: "{{ pwshScriptHome }}"