- name: set cluster info fact
  set_fact:
    cluster_exists: false

- name: Get AKS Clusters
  ignore_errors: True
  ansible.windows.win_shell:  "Get-AksHciCluster {{ cluster.clusterName }}| ConvertTo-Json"
  register: aks_cluster_info

- name: set cluster info fact
  set_fact:
    cluster_exists: true
  when: aks_cluster_info.stdout

- name: write aks env variables file
  template:
    src: remove_cluster_variables.ps1.j2
    dest: "{{ pwshScriptHome }}\\remove_cluster_variables.ps1"
  when: cluster_exists
  
- name: write remove aks cluster script to server
  ansible.windows.win_copy:
    src: remove_aks_cluster.ps1
    dest: "{{ pwshScriptHome }}\\remove_aks_cluster.ps1"
  when: cluster_exists

- name: set remove log file name
  set_fact:
    remove_log_file_name: "remove_aks_workload_{{ cluster.clusterName }}_{{ansible_date_time.epoch}}.log"
  when: cluster_exists
  
- name: Remove AKS cluster
  ansible.windows.win_shell: "{{ pwshScriptHome }}\\remove_aks_cluster.ps1 >> {{ pwshScriptLogs }}\\{{ remove_log_file_name }}"
  args:
    chdir: "{{ pwshScriptHome }}"
  when: cluster_exists