- name: write aks env variables file
  template:
    src: modify_cluster_variables.ps1.j2
    dest: "{{ pwshScriptHome }}\\modify_cluster_variables.ps1"
  
- name: write create aks cluster script to server
  ansible.windows.win_copy:
    src: files/update_aks_cluster.ps1
    dest: "{{ pwshScriptHome }}\\update_aks_cluster.ps1"

- name: set update log file name
  set_fact:
    update_log_file_name: "update_aks_workload_{{ cluster.clusterName }}_{{ansible_date_time.epoch}}.log"
  
- name: Update AKS cluster
  ansible.windows.win_shell: "{{ pwshScriptHome }}\\update_aks_cluster.ps1 >> {{ pwshScriptLogs }}\\{{ update_log_file_name }}"
  args:
    chdir: "{{ pwshScriptHome }}"